### PR TITLE
add new triggers for spotify

### LINKED ISSUE #59: add new triggers for "Spotify"
hi again. just had an ad go through that i'd never seen/heard before on Spotify.
Screenshot_20220620-020147

_Originally posted by @unseenlarks in https://github.com/aghontpi/ad-silence/issues/41#issuecomment-1159982540_

### PR DESCRIPTION
**Pull request by aghontpi**
refer #59

xml key value = "sas_interruption_title"

extracted from spotify vsersion: 8-7-16-1354

closes #59

### CODE REVIEW

**Comment by aghontpi** [comment]
```text
id_mod/decompiled/spotify-8742943/res/values/strings.xml:
ung_later_button_text">Dismiss</string>
ung_link_account_button_text">Activate</string>
interruption_title">Your song will play after this short message</string>
_profile_dialog_body_failed">Something went wrong. Give it another go?</string>
_profile_dialog_cancel_button">Cancel</string>
id_mod/decompiled/spotify-8742943/res/values-af/strings.xml:
ung_later_button_text">Weier</string>
ung_link_account_button_text">Aktiveer</string>
interruption_title">Jou liedjie gaan na hierdie kort boodskap speel</string>
_profile_dialog_body_failed">Iets het skeefgeloop. Wil jy weer ’n keer probeer?</string>
_profile_dialog_cancel_button">Kanselleer</string>
id_mod/decompiled/spotify-8742943/res/values-am/strings.xml:
ung_later_button_text">አሰናብት</string>
ung_link_account_button_text">አንቃ</string>
interruption_title">ሙዚቃዎ ከዚህ አጭር መልዕክት በኋላ ይጫወታል</string>
_profile_dialog_body_failed">የሆነ ስህተት ተከስቷል። እንደገና ይሞክር?</string>
_profile_dialog_cancel_button">ሰርዝ</string>
id_mod/decompiled/spotify-8742943/res/values-ar/strings.xml:
ung_later_button_text">تجاهل</string>
ung_link_account_button_text">تفعيل</string>
interruption_title">ستبدأ بالاستماع إلى أغنيتك بعد هذه الرسالة القصيرة</string>
_profile_dialog_body_failed">حدث خطأ ما. هل تريد إعادة المحاولة؟</string>
_profile_dialog_cancel_button">إلغاء</string>
id_mod/decompiled/spotify-8742943/res/values-az/strings.xml:
ung_later_button_text">Rədd et</string>
ung_link_account_button_text">Aktivləşdir</string>
interruption_title">Mahnın bu qısa mesajdan sonra oxudulacaq</string>
_profile_dialog_body_failed">Xəta baş verdi. Bir də cəhd edilsin?</string>
_profile_dialog_cancel_button">Ləğv et</string>
id_mod/decompiled/spotify-8742943/res/values-bg/strings.xml:
ung_later_button_text">Отхвърляне</string>
ung_link_account_button_text">Активирайте</string>
interruption_title">Песента ви ще се пусне след това кратко съобщение</string>
_profile_dialog_body_failed">Нещо се обърка. Опитайте пак?</string>
_profile_dialog_cancel_button">Отмяна</string>
id_mod/decompiled/spotify-8742943/res/values-bn/strings.xml:
ung_later_button_text">খারিজ করুন</string>
ung_link_account_button_text">চালু করুন</string>
interruption_title">আপনার গানটি এই সংক্ষিপ্ত বার্তার পরে চলবে</string>
_profile_dialog_body_failed">কিছু সমস্যা হয়েছে। আর একবার চেষ্টা করবেন?</string>
_profile_dialog_cancel_button">বাতিল করুন</string>
id_mod/decompiled/spotify-8742943/res/values-cs/strings.xml:
ung_later_button_text">Nemám zájem</string>
ung_link_account_button_text">Aktivovat</string>
interruption_title">Skladba se přehraje po této krátké zprávě.</string>
_profile_dialog_body_failed">Něco se pokazilo. Zkusíme to ještě jednou?</string>
_profile_dialog_cancel_button">Zrušit</string>
id_mod/decompiled/spotify-8742943/res/values-da/strings.xml:
ung_later_button_text">Afvis</string>
ung_link_account_button_text">Slå til</string>
interruption_title">Din sang afspilles efter denne korte meddelelse</string>
_profile_dialog_body_failed">Noget gik galt. Vil du prøve igen?</string>
_profile_dialog_cancel_button">Annuller</string>
id_mod/decompiled/spotify-8742943/res/values-de/strings.xml:
ung_later_button_text">Schließen</string>
ung_link_account_button_text">Aktivieren</string>
interruption_title">Deinen Song hörst du nach dieser kurzen Botschaft.</string>
_profile_dialog_body_failed">Irgendetwas ist schiefgelaufen. Willst du es nochmal versuchen?</string>
_profile_dialog_cancel_button">Abbrechen</string>
id_mod/decompiled/spotify-8742943/res/values-el/strings.xml:
ung_later_button_text">Απόρριψη</string>
ung_link_account_button_text">Ενεργοποίηση</string>
interruption_title">Το τραγούδι σου θα ξεκινήσει μετά από αυτό το σύντομο μήνυμα</string>
_profile_dialog_body_failed">Κάτι πήγε στραβά. Θέλεις να ξαναδοκιμάσεις;</string>
_profile_dialog_cancel_button">Ακύρωση</string>
id_mod/decompiled/spotify-8742943/res/values-es/strings.xml:
ung_later_button_text">Ignorar</string>
ung_link_account_button_text">Activar</string>
interruption_title">Tu canción se reproducirá después de este breve mensaje</string>
_profile_dialog_body_failed">Algo salió mal. ¿Quieres volver a intentarlo?</string>
_profile_dialog_cancel_button">Cancelar</string>
id_mod/decompiled/spotify-8742943/res/values-es-rES/strings.xml:
ung_later_button_text">Cerrar</string>
ung_link_account_button_text">Activar</string>
interruption_title">Tu canción sonará tras este breve mensaje.</string>
_profile_dialog_body_failed">Algo no ha ido como debía. ¿Lo intentamos otra vez?</string>
_profile_dialog_cancel_button">Cancelar</string>
id_mod/decompiled/spotify-8742943/res/values-et/strings.xml:
ung_later_button_text">Sule</string>
ung_link_account_button_text">Aktiveeri</string>
interruption_title">Sinu laul esitatakse pärast seda lühisõnumit</string>
_profile_dialog_body_failed">Midagi läks valesti. Kas proovida veel kord?</string>
_profile_dialog_cancel_button">Tühista</string>
id_mod/decompiled/spotify-8742943/res/values-fa/strings.xml:
ung_later_button_text">رد شدن</string>
ung_link_account_button_text">فعال کردن</string>
interruption_title">آهنگ شما بعد از این پیام کوتاه پخش خواهد شد</string>
_profile_dialog_body_failed">مشکلی روی داد. یک بار دیگر امتحان کنید؟</string>
_profile_dialog_cancel_button">لغو</string>
id_mod/decompiled/spotify-8742943/res/values-fi/strings.xml:
ung_later_button_text">Ohita</string>
ung_link_account_button_text">Aktivoi</string>
interruption_title">Kappale soi tämän lyhyen viestin jälkeen</string>
_profile_dialog_body_failed">Jotain meni pieleen. Haluatko yrittää uudelleen?</string>
_profile_dialog_cancel_button">Peruuta</string>
id_mod/decompiled/spotify-8742943/res/values-fr/strings.xml:
ung_later_button_text">Ignorer</string>
ung_link_account_button_text">Activer</string>
interruption_title">Votre titre se lancera après cette courte pub</string>
_profile_dialog_body_failed">"Une erreur s'est produite. Vous voulez faire une nouvelle 
_profile_dialog_cancel_button">Annuler</string>
id_mod/decompiled/spotify-8742943/res/values-fr-rCA/strings.xml:
ung_later_button_text">Ignorer</string>
ung_link_account_button_text">Activer</string>
interruption_title">Nous ferons jouer votre chanson après ce court message</string>
_profile_dialog_body_failed">"Une erreur s'est produite. Voulez-vous réessayer?"</string>
_profile_dialog_cancel_button">Annuler</string>
id_mod/decompiled/spotify-8742943/res/values-gu/strings.xml:
ung_later_button_text">કાઢી નાખો</string>
ung_link_account_button_text">એક્ટિવેટ કરો</string>
interruption_title">તમારું ગીત આ ટૂંકા સંદેશ પછી વાગશે</string>
_profile_dialog_body_failed">કંઈક ભૂલ થઈ. બીજી વાર પ્રયત્ન કરવા માંગો છો?</string>
_profile_dialog_cancel_button">રદ કરો</string>
id_mod/decompiled/spotify-8742943/res/values-hi/strings.xml:
ung_later_button_text">खारिज करें</string>
ung_link_account_button_text">एक्टिवेट करें</string>
interruption_title">आपका गाना इस छोटे से संदेश के बाद चलेगा</string>
_profile_dialog_body_failed">कोई गड़बड़ हुई. फिर से कोशिश करेंगे?</string>
_profile_dialog_cancel_button">कैंसिल करें</string>
id_mod/decompiled/spotify-8742943/res/values-hr/strings.xml:
ung_later_button_text">Odbaci</string>
ung_link_account_button_text">Aktiviraj</string>
interruption_title">Vaša pjesma reproducirat će se nakon ove kratke poruke</string>
_profile_dialog_body_failed">Došlo je do pogreške. Želite li ponovno pokušati?</string>
_profile_dialog_cancel_button">Odustani</string>
id_mod/decompiled/spotify-8742943/res/values-hu/strings.xml:
ung_later_button_text">Bezárás</string>
ung_link_account_button_text">Aktiválás</string>
interruption_title">A dal a rövid üzenet után indul</string>
_profile_dialog_body_failed">Valami hiba történt. Megpróbálod még egyszer?</string>
_profile_dialog_cancel_button">Mégse</string>
id_mod/decompiled/spotify-8742943/res/values-in/strings.xml:
ung_later_button_text">Tutup</string>
ung_link_account_button_text">Aktifkan</string>
interruption_title">Lagu kamu akan diputar setelah pesan singkat ini</string>
_profile_dialog_body_failed">Ada yang salah. Coba sekali lagi?</string>
_profile_dialog_cancel_button">Batalkan</string>
id_mod/decompiled/spotify-8742943/res/values-is/strings.xml:
ung_later_button_text">Loka</string>
ung_link_account_button_text">Virkja</string>
interruption_title">Lagið spilast eftir þessi stuttu skilaboð</string>
_profile_dialog_body_failed">Eitthvað fór úrskeiðis. Viltu reyna aftur?</string>
_profile_dialog_cancel_button">Hætta við</string>
id_mod/decompiled/spotify-8742943/res/values-it/strings.xml:
ung_later_button_text">Chiudi</string>
ung_link_account_button_text">Attiva</string>
interruption_title">Il brano inizierà dopo questo breve messaggio</string>
_profile_dialog_body_failed">Si è verificato un errore. Ancora un tentativo?</string>
_profile_dialog_cancel_button">Annulla</string>
id_mod/decompiled/spotify-8742943/res/values-iw/strings.xml:
ung_later_button_text">ביטול</string>
ung_link_account_button_text">הפעלה</string>
interruption_title">הישר יושמע אחרי ההודעה הקצרה הבאה</string>
_profile_dialog_body_failed">משהו השתבש. שננסה שוב?</string>
_profile_dialog_cancel_button">ביטול</string>
id_mod/decompiled/spotify-8742943/res/values-ja/strings.xml:
ung_later_button_text">閉じる</string>
ung_link_account_button_text">有効にする</string>
interruption_title">音楽は広告の後に再生されます</string>
_profile_dialog_body_failed">エラーが発生したようです。もう一度お試しください。</string>
_profile_dialog_cancel_button">キャンセル</string>
id_mod/decompiled/spotify-8742943/res/values-kn/strings.xml:
ung_later_button_text">ತ್ಯಜಿಸಿ</string>
ung_link_account_button_text">ಆ್ಯಕ್ಟಿವೇಟ್</string>
interruption_title">ಈ ಕಿರು ಸಂದೇಶದ ನಂತರ ನಿಮ್ಮ ಹಾಡು ಪ್ಲೇ ಆಗುತ್ತದೆ</string>
_profile_dialog_body_failed">ಏನೋ ತಪ್ಪಾಗಿದೆ. ಇನ್ನೊಂದು ಪ್ರಯತ್ನ ಮಾಡುವಿರಾ?</string>
_profile_dialog_cancel_button">ರದ್ದು</string>
id_mod/decompiled/spotify-8742943/res/values-ko/strings.xml:
ung_later_button_text">닫기</string>
ung_link_account_button_text">활성화하기</string>
interruption_title">짧은 광고 후에 곡이 재생됩니다.</string>
_profile_dialog_body_failed">문제가 발생했습니다. 다시 시도하시겠어요?</string>
_profile_dialog_cancel_button">취소하기</string>
id_mod/decompiled/spotify-8742943/res/values-lt/strings.xml:
ung_later_button_text">Atmesti</string>
ung_link_account_button_text">Aktyvuoti</string>
interruption_title">Daina bus paleista po šio trumpo pranešimo</string>
_profile_dialog_body_failed">Kažkas nepavyko. Bandyti dar kartą?</string>
_profile_dialog_cancel_button">Atšaukti</string>
id_mod/decompiled/spotify-8742943/res/values-lv/strings.xml:
ung_later_button_text">Noraidīt</string>
ung_link_account_button_text">Aktivizēt</string>
interruption_title">Tava dziesma tiks atskaņota pēc īsas ziņas</string>
_profile_dialog_body_failed">Radās problēma. Vai mēģināt vēlreiz?</string>
_profile_dialog_cancel_button">Atcelt</string>
id_mod/decompiled/spotify-8742943/res/values-ml/strings.xml:
ung_later_button_text">തള്ളിക്കളയുക</string>
ung_link_account_button_text">സജീവമാക്കുക</string>
interruption_title">ഈ ഹ്രസ്വ സന്ദേശത്തിന് ശേഷം നിങ്ങളുടെ ഗാനം പ്ലേ ചെയ്യും</string>
_profile_dialog_body_failed">എന്തോ കുഴപ്പം സംഭവിച്ചു. ഒരു ശ്രമം കൂടി നടത്തണോ?</string>
_profile_dialog_cancel_button">റദ്ദാക്കുക</string>
id_mod/decompiled/spotify-8742943/res/values-mr/strings.xml:
ung_later_button_text">डिसमिस करा</string>
ung_link_account_button_text">सक्रिय करा</string>
interruption_title">या छोट्याशा संदेशानंतर तुमचे गाणे प्ले केले जाईल</string>
_profile_dialog_body_failed">काहीतरी चूक झाली. अजून एक प्रयत्न करायचा का?</string>
_profile_dialog_cancel_button">रद्द करा</string>
id_mod/decompiled/spotify-8742943/res/values-ms/strings.xml:
ung_later_button_text">Ketepikan</string>
ung_link_account_button_text">Aktifkan</string>
interruption_title">Lagu anda akan dimainkan selepas pesanan ringkas ini</string>
_profile_dialog_body_failed">Ada yang tidak kena. Cuba sekali lagi?</string>
_profile_dialog_cancel_button">Batal</string>
id_mod/decompiled/spotify-8742943/res/values-mzn/strings.xml:
ung_later_button_text">رد شدن</string>
ung_link_account_button_text">فعال کردن</string>
interruption_title">آهنگ شما بعد از این پیام کوتاه پخش خواهد شد</string>
_profile_dialog_body_failed">مشکلی روی داد. یک بار دیگر امتحان کنید؟</string>
_profile_dialog_cancel_button">لغو</string>
id_mod/decompiled/spotify-8742943/res/values-nb/strings.xml:
ung_later_button_text">Avvis</string>
ung_link_account_button_text">Aktiver</string>
interruption_title">Låten din spilles av etter denne korte meldingen</string>
_profile_dialog_body_failed">Noe gikk galt. Vil du prøve igjen?</string>
_profile_dialog_cancel_button">Avbryt</string>
id_mod/decompiled/spotify-8742943/res/values-ne/strings.xml:
ung_later_button_text">खारेज गर्नुहोस्</string>
ung_link_account_button_text">सक्रिय गर्नुहोस्</string>
interruption_title">तपाईंको गीत यो छोटो सन्देश सकिएपछि बज्ने छ</string>
_profile_dialog_body_failed">केही समस्या भयो। एक पटक फेरि प्रयास गर्ने हो?</string>
_profile_dialog_cancel_button">रद्द गर्नुहोस्</string>
id_mod/decompiled/spotify-8742943/res/values-nl/strings.xml:
ung_later_button_text">Sluiten</string>
ung_link_account_button_text">Aanzetten</string>
interruption_title">Het nummer begint na deze korte reclameboodschap.</string>
_profile_dialog_body_failed">Er is iets fout gegaan. Nog een keer proberen?</string>
_profile_dialog_cancel_button">Annuleren</string>
id_mod/decompiled/spotify-8742943/res/values-or/strings.xml:
ung_later_button_text">ବରଖାସ୍ତ କରନ୍ତୁ</string>
ung_link_account_button_text">ସକ୍ରିୟ କରନ୍ତୁ</string>
interruption_title">ଆପଣଙ୍କର ଗୀତ ଏହି କ୍ଷୁଦ୍ର ବାର୍ତ୍ତା ପରେ ଚାଲିବ</string>
_profile_dialog_body_failed">କିଛି ଭୁଲ ହୋଇଗଲା। ଏହାକୁ ଆଉଥରେ ଦିଅନ୍ତୁ?</string>
_profile_dialog_cancel_button">ବାତିଲ୍ କରନ୍ତୁ</string>
id_mod/decompiled/spotify-8742943/res/values-pa-rIN/strings.xml:
ung_later_button_text">ਖਾਰਜ ਕਰੋ</string>
ung_link_account_button_text">ਕਿਰਿਆਸ਼ੀਲ ਕਰੋ</string>
interruption_title">ਤੁਹਾਡਾ ਗਾਣਾ ਇਸ ਛੋਟੇ ਸੁਨੇਹੇ ਤੋਂ ਬਾਅਦ ਚੱਲੇਗਾ</string>
_profile_dialog_body_failed">ਕੁਝ ਗਲਤ ਹੋਇਆ ਹੈ। ਇੱਕ ਵਾਰ ਹੋਰ ਕੋਸ਼ਿਸ਼ ਕਰਨੀ ਹੈ?</string>
_profile_dialog_cancel_button">ਰੱਦ ਕਰੋ</string>
id_mod/decompiled/spotify-8742943/res/values-pa-rPK/strings.xml:
ung_later_button_text">برخاست کرو</string>
ung_link_account_button_text">فعال کرو</string>
interruption_title">تہاڈا گانا ایس چھوٹے پیغام توں بعد چلایا جاوے گا</string>
_profile_dialog_body_failed">کجھ غلط ہو گیا اے۔ اک واری فیر کوشش کرو؟</string>
_profile_dialog_cancel_button">منسوخ کرو</string>
id_mod/decompiled/spotify-8742943/res/values-pl/strings.xml:
ung_later_button_text">Odrzuć</string>
ung_link_account_button_text">Aktywuj</string>
interruption_title">Utwór zostanie odtworzony po krótkim komunikacie.</string>
_profile_dialog_body_failed">Coś poszło nie tak. Spróbować ponownie?</string>
_profile_dialog_cancel_button">Anuluj</string>
id_mod/decompiled/spotify-8742943/res/values-pt-rBR/strings.xml:
ung_later_button_text">Ignorar</string>
ung_link_account_button_text">Ativar</string>
interruption_title">Sua música será reproduzida depois desta breve mensagem</string>
_profile_dialog_body_failed">Algo deu errado. Quer tentar de novo?</string>
_profile_dialog_cancel_button">Cancelar</string>
id_mod/decompiled/spotify-8742943/res/values-pt-rPT/strings.xml:
ung_later_button_text">Ignorar</string>
ung_link_account_button_text">Ativar</string>
interruption_title">A tua música será reproduzida após esta breve mensagem</string>
_profile_dialog_body_failed">Ocorreu um problema. Queres tentar outra vez?</string>
_profile_dialog_cancel_button">Cancelar</string>
id_mod/decompiled/spotify-8742943/res/values-ro/strings.xml:
ung_later_button_text">Închide</string>
ung_link_account_button_text">Activează</string>
interruption_title">Melodia ta se va reda după acest mesaj scurt</string>
_profile_dialog_body_failed">Ceva nu a funcționat corect. Încerci încă o dată?</string>
_profile_dialog_cancel_button">Anulează</string>
id_mod/decompiled/spotify-8742943/res/values-ru/strings.xml:
ung_later_button_text">Закрыть</string>
ung_link_account_button_text">Активировать</string>
interruption_title">Трек начнется после короткого сообщения</string>
_profile_dialog_body_failed">Что-то пошло не так. Попробовать еще раз?</string>
_profile_dialog_cancel_button">Отмена</string>
id_mod/decompiled/spotify-8742943/res/values-sk/strings.xml:
ung_later_button_text">Zrušiť</string>
ung_link_account_button_text">Aktivovať</string>
interruption_title">Skladba sa prehrá po tejto krátkej správe</string>
_profile_dialog_body_failed">Niečo sa nepodarilo. Skúsiš to znova?</string>
_profile_dialog_cancel_button">Zrušiť</string>
id_mod/decompiled/spotify-8742943/res/values-sl/strings.xml:
ung_later_button_text">Opusti</string>
ung_link_account_button_text">Aktiviraj</string>
interruption_title">Tvoja skladba se bo predvajala po tem kratkem sporočilu</string>
_profile_dialog_body_failed">Prišlo je do težave. Želiš poskusiti znova?</string>
_profile_dialog_cancel_button">Prekliči</string>
id_mod/decompiled/spotify-8742943/res/values-sr/strings.xml:
ung_later_button_text">Odbaci</string>
ung_link_account_button_text">Aktiviraj</string>
interruption_title">Pesma će se pustiti posle ove kratke poruke</string>
_profile_dialog_body_failed">Došlo je do greške. Želite ponovo da pokušate?</string>
_profile_dialog_cancel_button">Otkaži</string>
id_mod/decompiled/spotify-8742943/res/values-sv/strings.xml:
ung_later_button_text">Stäng</string>
ung_link_account_button_text">Aktivera</string>
interruption_title">Låten spelas upp efter det här korta meddelandet</string>
_profile_dialog_body_failed">Något blev fel. Vill du försöka igen?</string>
_profile_dialog_cancel_button">Avbryt</string>
id_mod/decompiled/spotify-8742943/res/values-sw/strings.xml:
ung_later_button_text">Ondoa</string>
ung_link_account_button_text">Wezesha</string>
interruption_title">Wimbo wako utachezwa baada ya ujumbe huu mfupi</string>
_profile_dialog_body_failed">Hitilafu fulani imetokea. Ungependa kujaribu tena?</string>
_profile_dialog_cancel_button">Ghairi</string>
id_mod/decompiled/spotify-8742943/res/values-ta/strings.xml:
ung_later_button_text">நிராகரி</string>
ung_link_account_button_text">செயல்படுத்து</string>
interruption_title">இந்தக் குறுகிய செய்திக்குப் பிறகு உங்கள் பாடல் பிளே ஆகும்</string>
_profile_dialog_body_failed">ஏதோ தவறு நடந்திருக்கிறது. இதை இன்னொரு முறை முயற்சி செய்யவா?</string>
_profile_dialog_cancel_button">ரத்துசெய்</string>
id_mod/decompiled/spotify-8742943/res/values-te/strings.xml:
ung_later_button_text">తీసివేయండి</string>
ung_link_account_button_text">యాక్టివేట్ చేయి</string>
interruption_title">ఈ చిన్న సందేశం తర్వాత మీ పాట ప్లే అవుతుంది</string>
_profile_dialog_body_failed">ఏదో తప్పు జరిగింది. మరొకటి ఉందా?</string>
_profile_dialog_cancel_button">రద్దు చేయండి</string>
id_mod/decompiled/spotify-8742943/res/values-th/strings.xml:
ung_later_button_text">ปิด</string>
ung_link_account_button_text">เปิดใช้งาน</string>
interruption_title">เพลงของคุณจะเล่นหลังสิ้นสุดข้อความสั้นๆ นี้</string>
_profile_dialog_body_failed">มีข้อผิดพลาดบางประการ ลองอีกครั้งไหม?</string>
_profile_dialog_cancel_button">ยกเลิก</string>
id_mod/decompiled/spotify-8742943/res/values-tl/strings.xml:
ung_later_button_text">I-dismiss</string>
ung_link_account_button_text">I-activate</string>
interruption_title">"Magpe-play ang kanta mo pagkatapos ng patalastas na 'to"</string>
_profile_dialog_body_failed">Nagkaproblema. Subukan ulit?</string>
_profile_dialog_cancel_button">I-cancel</string>
id_mod/decompiled/spotify-8742943/res/values-tr/strings.xml:
ung_later_button_text">Kapat</string>
ung_link_account_button_text">Etkinleştir</string>
interruption_title">Şarkın bu kısa mesajdan sonra çalacak</string>
_profile_dialog_body_failed">Bir sorun oluştu. Tekrar denemek ister misin?</string>
_profile_dialog_cancel_button">İptal et</string>
id_mod/decompiled/spotify-8742943/res/values-uk/strings.xml:
ung_later_button_text">Закрити</string>
ung_link_account_button_text">Активувати</string>
interruption_title">Пісня відтвориться після цього короткого повідомлення</string>
_profile_dialog_body_failed">Сталася помилка. Спробувати ще раз?</string>
_profile_dialog_cancel_button">Скасувати</string>
id_mod/decompiled/spotify-8742943/res/values-ur/strings.xml:
ung_later_button_text">برخاست کریں</string>
ung_link_account_button_text">فعال کریں</string>
interruption_title">آپ کا گانا اس مختصر میسج کے بعد پلے ہوگا</string>
_profile_dialog_body_failed">کچھ خرابی پیش آگئی ہے۔ ایک اور بار کوشش کرنا چاہتے ہیں؟</string>
_profile_dialog_cancel_button">منسوخ کریں</string>
id_mod/decompiled/spotify-8742943/res/values-vi/strings.xml:
ung_later_button_text">Bỏ qua</string>
ung_link_account_button_text">Kích hoạt</string>
interruption_title">Bài hát của bạn sẽ phát sau thông điệp ngắn này</string>
_profile_dialog_body_failed">Đã xảy ra lỗi. Bạn có muốn thử lại không?</string>
_profile_dialog_cancel_button">Hủy</string>
id_mod/decompiled/spotify-8742943/res/values-zh/strings.xml:
ung_later_button_text">撤销</string>
ung_link_account_button_text">激活</string>
interruption_title">你的歌曲将在此短信送达后播放</string>
_profile_dialog_body_failed">出错了。再试一次？</string>
_profile_dialog_cancel_button">取消</string>
id_mod/decompiled/spotify-8742943/res/values-zh-rHK/strings.xml:
ung_later_button_text">關閉</string>
ung_link_account_button_text">啟用</string>
interruption_title">你的歌曲將在這則簡短訊息後播放</string>
_profile_dialog_body_failed">發生錯誤。再試一次？</string>
_profile_dialog_cancel_button">取消</string>
id_mod/decompiled/spotify-8742943/res/values-zh-rTW/strings.xml:
ung_later_button_text">關閉</string>
ung_link_account_button_text">啟用</string>
interruption_title">你的歌曲將在這則簡短訊息後播放</string>
_profile_dialog_body_failed">發生錯誤。再試一次？</string>
_profile_dialog_cancel_button">取消</string>
id_mod/decompiled/spotify-8742943/res/values-zu/strings.xml:
ung_later_button_text">Chitha</string>
ung_link_account_button_text">Lenze lisebenze</string>
interruption_title">Ingoma yakho izodlala ngemva kwalo myalezo omfushane</string>
_profile_dialog_body_failed">Kukhona okungahambanga kahle. Uyakuzama futhi?</string>
_profile_dialog_cancel_button">Khansela</string>
```

**Comment by aghontpi** [comment]
(rename .zip to .apk, restrictions in comments)
[ad-silence-test-33.zip](https://github.com/aghontpi/ad-silence/files/9041548/ad-silence-test-33.zip)

**Comment by aghontpi** [comment]
[spotify - add new triggers for ads detection](https://trello.com/c/NUmcca8K/54-spotify-add-new-triggers-for-ads-detection)

**Comment by unseenlarks** [comment]
> (rename .zip to .apk, restrictions in comments) [ad-silence-test-33.zip](https://github.com/aghontpi/ad-silence/files/9041548/ad-silence-test-33.zip)

thank you very much. testing this version; so far detected two of the new ads which were successfully muted. only after one of them, the volume wasn't restored when the ad ended/the following track started playing. not sure how to repro, or if it was a one-off.

**Comment by aghontpi** [comment]
@unseenlarks thanks

I am also testing it, but I do not see the new ads tho.

 please do let me know if you further face "volume not restoring" 

if you want to dig deeper, filter the logcat with `NotificationParser`.

**Pull request merged**
