### PR TITLE
Fix "ads" not detected in spotify

### LINKED ISSUE #29: ads not muted on Spotify / Android 8
using a Sony Xperia X, running Android 8.0
Spotify version currently 8.7.8.233
Ad-silence version 0.5.2

Ad-silence has notification access and is enabled to mute ads. Spotify is enabled under 'select apps', and the Ad-silence notification is always visible on the notification drawer, regardless of Spotify status. battery optimisation is disabled for Ad-silence.

when ads are playing, the Ad-silence notification displays 'listening for ads', same as when music plays, or when Spotify itself is closed.

i also use Spotify Lite, but ads are muted every time (except for the final second), though.

let me know if i can provide any more information. thank you for your time.

### PR DESCRIPTION
**Pull request by aghontpi**
**this pr fixes #29**

The issue occurs because of different language locale.

A new file is created for "ad detection", any new words or false positives can be added or removed by changing this file.
```
app/src/main/java/bluepie/ad_silence/triggers/Spotify.kt
```

### CODE REVIEW

**Comment by aghontpi** [comment]
test build (rename to .apk, restrictions in comments)
[ad-silence-test-build-29.zip](https://github.com/aghontpi/ad-silence/files/8378661/ad-silence-test-build-29.zip)

**Comment by unseenlarks** [comment]
> test build (rename to .apk, restrictions in comments) [ad-silence-test-build-29.zip](https://github.com/aghontpi/ad-silence/files/8378661/ad-silence-test-build-29.zip)

success! thank you very much. :smiley:

**Comment by unseenlarks** [comment]
hi again. just had an ad go through that i'd never seen/heard before on Spotify.
Screenshot_20220620-020147

**Comment by aghontpi** [comment]
@unseenlarks, thanks for the report, did it occur more than once?

should we add this to `app/src/main/java/bluepie/ad_silence/triggers/Spotify.kt` ?
Screenshot 2022-07-01 at 11 11 54 AM

**Comment by unseenlarks** [comment]
the full text would be something like 'your song will play after the ad'.

it happened twice during that listening session, but to be fair, i haven't encountered it since. i haven't been listening much this week, but all the other ads i got were muted, as usual.

**Comment by unseenlarks** [comment]
caught this again today, the full ad reads "your song will play after this short message".
spotify-ad

**Comment by aghontpi** [comment]
@unseenlarks thanks, I was able to extract strings for all languages from the latest version, can you check https://github.com/aghontpi/ad-silence/blob/2bc7ce6529bf7d2b98b79a4fd9d3675b380ac6bf/app/src/main/java/bluepie/ad_silence/triggers/Spotify.kt#L80 in #62, some extracted string has `.` at the end..but others do not. idk which one is correct.

**Comment by unseenlarks** [comment]
i see "Tu canción se reproducirá después de este breve mensaje". while the other string seems to be for es-rES locale (Spain Spanish).

**Comment by aghontpi** [comment]
hmm, 🤔 okey

**Pull request merged**
